Updated date range arrow to single character #1058
mattermost/focalboard pull request #1064
Opened 2021-08-21 10:29 UTC by DeviousLab

#### Summary
Switches the arrow in a date range from `->` to `→` as requested
![image](https://user-images.githubusercontent.com/53790060/130318949-fb71ee1c-b892-4d4d-8d93-2e50c3bbf06a.png)

#### Ticket Link
  Aims to resolve https://github.com/mattermost/focalboard/issues/1058

2021-08-21 10:29 UTC, mattermod commented
Hello @DeviousLab,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-08-21 10:33 UTC, DeviousLab commented
/check-cla

2021-08-23 12:27 UTC, hahmadia approved these changes

2021-08-23 12:28 UTC, hahmadia commented
Hi! Could you please fix the snapshot test that are failing? Thank you

2021-08-23 13:06 UTC, DeviousLab commented
https://github.com/mattermost/focalboard/blob/e8eeb5104670d94bb31cb2ab4a82cc5d0a75dafe/webapp/src/components/properties/dateRange/dateRange.test.tsx#L158

https://github.com/mattermost/focalboard/blob/e8eeb5104670d94bb31cb2ab4a82cc5d0a75dafe/webapp/src/components/properties/dateRange/dateRange.test.tsx#L195

https://github.com/mattermost/focalboard/blob/e8eeb5104670d94bb31cb2ab4a82cc5d0a75dafe/webapp/src/components/properties/dateRange/dateRange.test.tsx#L230

Am I correct in assuming that these are the lines causing Jest to fail?

2021-08-23 14:05 UTC, harshilsharma63 approved these changes
Looks good but we need to update the tests.

2021-08-23 17:01 UTC, kamre commented
@DeviousLab here are the [log messages about failures](https://github.com/mattermost/focalboard/pull/1064/checks?check_run_id=3400213587#step:11:24). So it looks like you need to fix two things:
* update jest snapshots via executing `npm run updatesnapshots` from `webapp` folder
* update names inside these three calls of `getByRole` that you have already found

2021-08-23 18:47 UTC, DeviousLab commented
Ran `npm run updatesnapshots` after updating the names in dateRange.test.tsx and all tests passed.

2021-08-23 18:58 UTC, hahmadia approved these changes

2021-08-23 20:59 UTC, DeviousLab commented
> @DeviousLab did you forget to commit the updated snapshots?

My bad, wasn't aware that they were necessary to commit!

2021-08-23 21:06 UTC, hahmadia requested changes

2021-08-23 21:06 UTC, hahmadia commented on webapp/src/components/cardDetail/__snapshots__/cardDetailContents.test.tsx.snap
> +        class="MarkdownEditor octo-editor  "
I don't think this file needs change. I think you can uncommit the changes in this file.

2021-08-23 21:37 UTC, DeviousLab commented
Removed the other file from the commit now

2021-08-23 22:03 UTC, hahmadia approved these changes

2021-08-23 22:22 UTC, merged