[GH-824] Add unit test for addContentMenuItem
mattermost/focalboard pull request #1073
Opened 2021-08-23 23:02 UTC by jufab

#### Summary

Add unit test for addContentMenuItem.
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/824

2021-08-23 23:02 UTC, mattermod commented
Hello @jufab,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-08-24 22:44 UTC, sbishel requested changes
Thanks for your contribution. Rather than write individual tests for each block type. I would suggest using `contentRegistry.contentTypes`. Similar to how it is used in `contentBlock`. And loop through each valid contentType using `test.each()`, doing a `toMatchSnapshot` on each.

2021-08-30 04:55 UTC, wiggin77 approved these changes
LGTM :+1:

2021-08-30 19:25 UTC, sbishel approved these changes
Nice..thank you.

2021-08-30 19:25 UTC, merged