423 | Added unit tests for files.go
mattermost/focalboard pull request #1119
Opened 2021-08-27 07:03 UTC by Prassud

#### Summary
Added Unit test cases for server/app/files.go using mocked fileBackend

#### Ticket Link
[Link](https://github.com/mattermost/focalboard/issues/423)

2021-08-30 04:53 UTC, wiggin77 approved these changes
LGTM :+1:   Great work @Prassud

2021-08-30 22:09 UTC, sbishel requested changes
A couple more Lint errors otherwise LGTM

2021-08-31 04:25 UTC, Prassud commented
@sbishel Fixed Lint errors, could you verify once again?

2021-08-31 22:08 UTC, sbishel approved these changes

2021-08-31 22:08 UTC, merged