[GH-1013] Fix visibility of clear button for select option
mattermost/focalboard pull request #1160
Opened 2021-09-08 15:35 UTC by kamre

#### Summary
Show clear button for (multi) select property only when it is being edited:
- set open state to `false` on `blur` event for (multi) select property
- files for `MultiSelectProperty` component moved into separate folder
- extracted new `SelectProperty` component from the code inside `PropertyValueElement`
- unit test for new component added
- minor improvements for styles for `Label` component

Here is how it looks for the table:
![Select_MultiSelect_Table](https://user-images.githubusercontent.com/5587620/132539936-46a4e7e4-9be1-4526-8c7e-a28380dd2428.gif)

For the card dialog:
![Select_MultiSelect_CardDialog](https://user-images.githubusercontent.com/5587620/132539967-092b69df-2006-4b0d-8f38-7ccf6919bd08.gif)

#### Ticket Link
Fixes #1013

2021-09-08 15:35 UTC, mattermod commented
Hello @kamre,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-09-13 22:52 UTC, sbishel requested changes
Looks awesome. Thanks @kamre Looks like some tests failed after I sync'ed to main. Could you update and I'll get this merged.

2021-09-13 22:52 UTC, sbishel commented on webapp/src/components/properties/select/select.test.tsx
> +})
Nice tests and coverage...

2021-09-13 22:52 UTC, sbishel commented on webapp/src/components/properties/select/select.tsx
> +export default SelectProperty
I like this enhancement.

2021-09-14 15:38 UTC, kamre commented
@sbishel updated jest snapshot.

2021-09-14 21:35 UTC, sbishel approved these changes

2021-09-14 21:35 UTC, merged