FTUE - Dashboard
mattermost/focalboard pull request #1177
Opened 2021-09-10 10:38 UTC by harshilsharma63

#### Summary
FTUE part 1 - Personal Dashboard

#### Ticket Link
https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/7e38eab4-890a-4fc3-8f48-a1f9bd1ab822?c=3a4c80ae-7cd6-49eb-8257-ea0c11f63723

2021-09-10 14:30 UTC, justinegeffen reviewed
Some minor edits and a suggested rewrite for the results content. Happy to discuss that further!

2021-09-10 14:30 UTC, justinegeffen commented on webapp/src/components/workspaceSwitcher/__snapshots__/workspaceSwitcher.test.tsx.snap
> +         1 result available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu.
```suggestion
         1 result available. Use the Up and Down arrows on your keyboard to choose options. Press Enter to select the currently focused option. Press Escape to exit the menu.
```

2021-09-10 14:30 UTC, justinegeffen commented on webapp/src/components/workspaceSwitcher/__snapshots__/workspaceSwitcher.test.tsx.snap
> +         3 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu.
```suggestion
         3 results available. Use the Up and Down arrows on your keyboard to choose options. Press Enter to select the currently focused option. Press Escape to exit the menu.
```

2021-09-10 14:30 UTC, justinegeffen commented on webapp/src/components/workspaceSwitcher/__snapshots__/workspaceOptions.test.tsx.snap
> +         1 result available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu.
```suggestion
         1 result available. Use the Up and Down arrows on your keyboard to choose options. Press Enter to select the currently focused option. Press Escape to exit the menu.
```

2021-09-10 14:30 UTC, justinegeffen commented on webapp/src/components/workspaceSwitcher/__snapshots__/workspaceOptions.test.tsx.snap
> +         3 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu.
```suggestion
         3 results available. Use the Up and Down arrows on your keyboard to choose options. Press Enter to select the currently focused option. Press Escape to exit the menu.
```

2021-09-13 14:36 UTC, justinegeffen approved these changes

2021-09-13 17:04 UTC, sbishel requested changes
I ran into a few issues while testing - 

It matches figma, so more a question for @asaadmahmood, the button to hide the sidebar is no longer available.
<img width="251" alt="Screen Shot 2021-09-13 at 10 41 39 AM" src="https://user-images.githubusercontent.com/12704875/133126599-8b236a52-2bea-43bb-aab4-8b8973ba94e6.png">

When in Dashboard, "Add Board" should not be available. (It actually adds to last viewed board, if you add a board)
<img width="524" alt="Screen Shot 2021-09-13 at 8 50 29 AM" src="https://user-images.githubusercontent.com/12704875/133126326-ef5aca7c-bc5f-434a-a13d-5424cd85884f.png">

Direct channels Title does not display in either Dropdown or Dashboard. Group messages appear fine.
<img width="1266" alt="Screen Shot 2021-09-13 at 8 49 14 AM" src="https://user-images.githubusercontent.com/12704875/133126488-03ac5b43-2ead-4b1b-97fe-bd2850546189.png">


<img width="259" alt="Screen Shot 2021-09-13 at 8 49 30 AM" src="https://user-images.githubusercontent.com/12704875/133126329-97b2ae97-7aeb-42c8-a241-36f7596472a0.png">

<img width="244" alt="Screen Shot 2021-09-13 at 10 40 21 AM" src="https://user-images.githubusercontent.com/12704875/133126202-ae2febc9-4a8a-4a46-af8d-28c1fdb97cfd.png">

2021-09-14 07:02 UTC, harshilsharma63 commented
@sbishel 

> When in Dashboard, "Add Board" should not be available. (It actually adds to last viewed board, if you add a board)

Fixed. It's now hidden in the dashboard view.

> Direct channels Title does not display in either Dropdown or Dashboard. Group messages appear fine

It was already fixed in a separate PR (#1179).
<img width="278" alt="Screenshot 2021-09-14 at 12 30 48 PM" src="https://user-images.githubusercontent.com/18575143/133210673-020ed60d-34b5-4988-a42b-cfe1c31e3102.png">
<img width="1432" alt="Screenshot 2021-09-14 at 12 31 07 PM" src="https://user-images.githubusercontent.com/18575143/133210680-2f5ffcfa-55f8-4434-afb7-8bc1368ed854.png">

2021-09-14 07:02 UTC, harshilsharma63 commented on webapp/src/components/sidebar/sidebar.tsx
> +                                {'Use the switcher to easily change channels'}
Done.

2021-09-14 07:02 UTC, harshilsharma63 commented on webapp/src/components/sidebar/sidebar.tsx
> +                <WorkspaceSwitcher activeWorkspace={workspace}/>
Combining that with `workspace && workspace.id !== '0'` was making it look messy, so didn't do it.

2021-09-14 12:52 UTC, justinegeffen commented
Added the docs needed label as the docs will need to be updated, but it's not a blocker to merge.

2021-09-14 16:40 UTC, sbishel approved these changes
Approving and merging. I did create a bug related to this PR or https://github.com/mattermost/focalboard/pull/1179

https://github.com/mattermost/focalboard/issues/1205

2021-09-14 16:42 UTC, merged