Typing adjustment - 1353
mattermost/focalboard pull request #1415
Opened 2021-10-03 03:56 UTC by tiago154

#### Summary

Hello.

Adjusted the warnings in the file
`webapp/src/hooks/sortable.tsx`

where the typing from `any` to `unknown` was changed.

#### Ticket Link

#1353

2021-10-03 03:56 UTC, mattermod commented
Hello @tiago154,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-10-04 16:17 UTC, hahmadia requested changes
Hello! Thank you for the changes!

I noticed that some of the work you've done can be simplified even further by the use of Generic types. That way, we don't have to restrict the types if we plan to use these function  for other types in the future. I'm okay with leaving `useSortableWithGrip` as it is but `useSortable` should be made generic where the `handler` function should handle the `item` of type `T` instead of having a type that unions all of them (In our case that doesn't make a lot of sense since we are never passing a type that has the properties of Card and IPropertyTemplate and so on and so forth). 

Hopefully this makes sense and let me know if you need any assistance.

2021-10-04 16:17 UTC, hahmadia commented on webapp/src/hooks/sortable.tsx
> +export function useSortable(itemType: string, item: SortableItem, enabled: boolean, handler: (src: HandlerItem, st: HandlerItem) => void): [boolean, boolean, React.RefObject<HTMLDivElement>] {
We can Simplify this by using Generics. Something like the following

```suggestion
export function useSortable<T>(itemType: string, item: T, enabled: boolean, handler: (src: T, st: T) => void): [boolean, boolean, React.RefObject<HTMLDivElement>] {
```

2021-10-04 16:17 UTC, hahmadia commented on webapp/src/hooks/sortable.tsx
> +function useSortableBase(itemType: string, item: SortableItem | ISortableWithGripItem, enabled: boolean, handler: (src: HandlerBaseItem, st: HandlerBaseItem) => void): [boolean, boolean, DragElementW
```suggestion
function useSortableBase<T>(itemType: string, item: T, enabled: boolean, handler: (src: T, st: T) => void): [boolean, boolean, DragElementWrapper<DragSourceOptions>, DragElementWrapper<DragSourceOptions>, DragElementWrapper<DragPreviewOptions>] {
```

2021-10-04 16:17 UTC, hahmadia commented on webapp/src/hooks/sortable.tsx
> +            handler(dragItem, item as HandlerBaseItem)
```suggestion
        drop: (dragItem: T) => {
            handler(dragItem, item)
```

2021-10-04 16:17 UTC, hahmadia commented on webapp/src/hooks/sortable.tsx
> +export function useSortableWithGrip(itemType: string, item: ISortableWithGripItem, enabled: boolean, handler: (src: IContentBlockWithCords, st: IContentBlockWithCords) => void): [boolean, boolean, Re
I'm okay with leavin this the way it is.

2021-10-04 17:33 UTC, tiago154 commented
> Hello! Thank you for the changes!
> 
> I noticed that some of the work you've done can be simplified even further by the use of Generic types. That way, we don't have to restrict the types if we plan to use these function for other types in the future. I'm okay with leaving `useSortableWithGrip` as it is but `useSortable` should be made generic where the `handler` function should handle the `item` of type `T` instead of having a type that unions all of them (In our case that doesn't make a lot of sense since we are never passing a type that has the properties of Card and IPropertyTemplate and so on and so forth).
> 
> Hopefully this makes sense and let me know if you need any assistance.

@hahmadia 

It makes perfect sense what you explained.
I made the changes for using Generics. Please confirm that everything is all right now.
Thanks in advance.

2021-10-05 22:55 UTC, merged