Changed div to button for octo-sidebar-item
mattermost/focalboard pull request #1552
Opened 2021-10-13 16:40 UTC by anirudhprabhakaran3

#### Summary

Converted octo-sidebar-item from div to button
#### Ticket Link

https://github.com/mattermost/focalboard/issues/1513

2021-10-18 18:47 UTC, hahmadia commented
/update-branch

2021-11-02 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-11-02 13:47 UTC, hahmadia commented
@jespino Friendly Bump

2021-11-02 13:52 UTC, jespino commented on webapp/src/components/sidebar/sidebarBoardItem.tsx
> +                </button>}
This is wrong, you are closing a button, but opening a div. I guess it was as part of reverting the last change.

2021-11-02 13:52 UTC, jespino requested changes
A tiny error, otherwise looks good to me.

2021-11-02 15:00 UTC, hahmadia commented
Could we also get the broken tests fixed. Thanks

2021-11-02 15:57 UTC, hahmadia approved these changes

2021-11-03 17:29 UTC, hahmadia commented
Can you please fix the broken cypress test? After that, you can re-request a review.

2021-11-05 17:24 UTC, emilyacook commented
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @anirudhprabhakaran3

2021-11-06 05:06 UTC, anirudhprabhakaran3 commented
Hello! I'll finish working on the issue by tomorrow, and then claim the sticker set if that's okay. Thanks!

2021-11-06 06:42 UTC, anirudhprabhakaran3 commented
@hahmadia could you approve the workflows? I'll work on the tests if any fail

2021-11-08 13:55 UTC, hahmadia commented
Broken Tests can be seen now

2021-11-10 09:42 UTC, anirudhprabhakaran3 commented
Hello!
So i was trying to fix the cypress tests. However, when i tried to run the tests on the main branch, I'm still getting the same error. Is the issue in the cypress test itself?

2021-11-21 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2022-07-04 05:02 UTC, closed without merging