[GH-1694] Fix the issue where clicking on the + button at the top of a board group wouldn't open the newly-added card
mattermost/focalboard pull request #1708
Opened 2021-10-31 14:03 UTC by ironbyte

#### Summary
* Fix the issue where clicking on the + button at the top of a board group wouldn't open the newly-added card

#### Ticket Link
#1694

2021-10-31 14:03 UTC, mattermod commented
Hello @ironbyte,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-10-31 14:11 UTC, ironbyte commented
/check-cla

2021-11-01 05:08 UTC, harshilsharma63 reviewed
Changes look good and work fine. Can you also add some tests for this?

2021-11-01 05:08 UTC, harshilsharma63 requested changes
Changes look good and work fine. Can you also add some tests for this?

2021-11-01 05:22 UTC, ironbyte commented
@harshilsharma63 Shot. Ok, will do!

2021-11-02 04:18 UTC, ironbyte commented
> Changes look good and work fine. Can you also add some tests for this?

Just update `webapp/cypress/integration/createBoard.js` file?

2021-11-03 12:19 UTC, harshilsharma63 commented
> Just update `webapp/cypress/integration/createBoard.js` file?

Either that if you wanna write an integration test, or create a new `kanbanColumnHeader.test.tsx` for the unit test. Whichever you're wanna pick.

2021-11-05 17:41 UTC, emilyacook commented
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @ironbyte

2021-11-07 10:02 UTC, ironbyte commented
> > Just update `webapp/cypress/integration/createBoard.js` file?
> 
> Either that if you wanna write an integration test, or create a new `kanbanColumnHeader.test.tsx` for the unit test. Whichever you're wanna pick.

Hey, sorry for the delay in getting back to this. I've updated `createBoard` test spec accordingly. I'm sure if I should add a new cypress test spec just for testing the + button functionality.

2021-11-09 00:38 UTC, sbishel approved these changes

2021-11-15 09:26 UTC, harshilsharma63 approved these changes

2021-11-15 09:26 UTC, harshilsharma63 commented
@ironbyte changes look good now. LGTM!

2021-11-15 09:26 UTC, merged