Fixed sort by date
mattermost/focalboard pull request #1719
Opened 2021-11-02 11:53 UTC by sarvani1997

#### Summary

Date property is in JSON string. So, we should parse it and sort later.

#### Ticket Link

Fixes https://github.com/mattermost/focalboard/issues/1664

2021-11-02 11:53 UTC, mattermod commented
Hello @sarvani1997,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-11-02 20:05 UTC, wiggin77 requested changes
Looks good @sarvani1997.  Thanks.  There is one typing issue to fix and then it's good to go.

2021-11-03 11:23 UTC, harshilsharma63 approved these changes

2021-11-09 15:22 UTC, sbishel commented
/update-branch

2021-11-09 20:38 UTC, wiggin77 approved these changes
LGTM :+1:

2021-11-09 20:39 UTC, merged