Added search in properties of a card
mattermost/focalboard pull request #222
Opened 2021-03-31 21:59 UTC by BharatKalluri

#### Summary

Search now also searches in the properties of the card along with the name. 

#### Ticket Link

https://github.com/mattermost/focalboard/issues/128

2021-03-31 21:59 UTC, mattermod commented
Hello @BharatKalluri,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-03-31 22:55 UTC, chenilim requested changes
Thanks for the PR @BharatKalluri! A couple perf improvement requests.

2021-03-31 22:55 UTC, chenilim commented on webapp/src/viewModel/boardTree.ts
> +                some((el: boolean) => el)
* Replace this with a forEach loop and return true early on a match
* You should also be able to write `card.properties.forEach(...`

2021-04-01 07:57 UTC, BharatKalluri commented on webapp/src/viewModel/boardTree.ts
> +            const searchTextInCardTitle: boolean = card.title?.toLocaleLowerCase().includes(searchText)
Agreed 👍🏽 
Made changes @ https://github.com/mattermost/focalboard/pull/222/commits/0b02ddfc4bf7bb4a42ae510e20d196405d846232

2021-04-01 17:22 UTC, chenilim approved these changes
Thanks for the updated @BharatKalluri! I realized there are a few more subtleties with handling select property types. I'll merge this PR and edit. Thank you for the contribution!

2021-04-01 17:22 UTC, merged