wrap registration block to catch error
mattermost/focalboard pull request #2299
Opened 2022-02-08 23:17 UTC by sbishel

#### Summary
Fixes issue when running against an older mattermost-server that does not implement `registry.registerChannelIntroButtonAction`

#### Ticket Link
https://github.com/mattermost/focalboard/issues/2251

2022-02-09 05:36 UTC, harshilsharma63 approved these changes
This works for now but can we update this to match the existing pattern? Currently, we check if `this.registry.<some hook>` is truthy, and use it if so.

For example this line https://github.com/mattermost/focalboard/blob/9d12efa2a2577336c25cfc7a99e6bcc11f860106/mattermost-plugin/webapp/src/index.tsx#L135

2022-02-09 12:26 UTC, jespino commented on mattermost-plugin/webapp/src/index.tsx
> +            try {
I think I prefer a this way:
```ts
// backward compatiblity for version < v6.5
if (registry.registerChannelIntroButtonAction) {
    this.channelHeaderButtonId = registry.registerChannelIntroButtonAction(<FocalboardIcon/>, goToFocalboardTemplate, 'Boards')
}
```

2022-02-09 12:27 UTC, jespino requested changes
I think I prefer a different way that doesn't mask possible unrelated errors.

2022-02-14 15:41 UTC, sbishel commented
/update-branch

2022-02-15 19:17 UTC, merged