Don't use property value for key construction.
mattermost/focalboard pull request #2317
Opened 2022-02-11 13:05 UTC by kamre

#### Summary
Usage of property value in key construction leads to unmount/remount for property value component when the value is changed.

This can sometimes cause a [failure in Cypress test](https://github.com/mattermost/focalboard/runs/5097312160?check_suite_focus=true) `cardURLProperty.ts` because the button that was found by Cypress will be detached from DOM after remount of react component.

#### Ticket Link
No linked ticket.

2022-02-11 13:05 UTC, mattermod commented
Hello @kamre,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-02-14 06:11 UTC, harshilsharma63 commented
@kamre having the same card open in two tabs and updating a date property in one tab is not updating it in the other tab. It works on `main` though. Can you verify that?

2022-02-14 06:11 UTC, harshilsharma63 requested changes
Date property changes not being propagated to WebSocket.

2022-02-14 08:07 UTC, kamre commented
@harshilsharma63 this is just how `DateRange` is [written currently](https://github.com/mattermost/focalboard/blob/02b50275ee5b011b9f306f07b2cb423ef83a74e7/webapp/src/components/properties/dateRange/dateRange.tsx#L71), i.e. `value` passed in props is only used as _initial value and not current_ value. 

In general this is not a good practice as you can [read here](https://overreacted.io/writing-resilient-components/#principle-1-dont-stop-the-data-flow) for example. I will look into how this can be improved.

2022-02-14 08:29 UTC, harshilsharma63 commented
Ah, okay, it was working on `main` because value itself was being used element key, forcing react to update the component. I can look into making the date property work if you want. LMK.

2022-02-15 06:16 UTC, harshilsharma63 approved these changes
LGTM!

2022-02-15 16:24 UTC, merged