Add SECURITY.md
mattermost/focalboard pull request #2349
Opened 2022-02-16 13:24 UTC by oh6hay

Content is as in other key repositories, eg. mattermost-mobile.

2022-02-16 16:05 UTC, wiggin77 requested changes

2022-02-16 16:05 UTC, wiggin77 commented on SECURITY.md
> +If you have feedback or suggestions on improving this policy document, please [create an issue](https://github.com/mattermost/mattermost-mobile/issues/new).
```suggestion
If you have feedback or suggestions on improving this policy document, please [create an issue](https://github.com/mattermost/focalboard/issues/new/choose).
```

2022-03-11 20:54 UTC, chenilim commented
@oh6hay, just following up on this. Sorry, I wan't sure if it needed my review - looks like Doug requested a change. Was there anything else? Should we link to this file from anywhere?

2022-03-12 00:00 UTC, oh6hay commented
> @oh6hay, just following up on this. Sorry, I wan't sure if it needed my review - looks like Doug requested a change. Was there anything else? Should we link to this file from anywhere?

hi! thanks @wiggin77 for spotting the copypaste error in the SECURITY.md. @chenilim No it doesn't need to be linked from anywhere, SECURITY.md is a standard location for a security policy file. Thanks guys!

2022-03-12 17:24 UTC, wiggin77 approved these changes

2022-03-18 17:55 UTC, chenilim approved these changes
Thanks all!

2022-03-18 17:55 UTC, merged