Shows "(Deleted User)" instead of long, unreadable UUID in case the u…
mattermost/focalboard pull request #2354
Opened 2022-02-17 09:50 UTC by akkivasu

…ser is not found

In case a user is not found, at present unreadable and long UUIDs are shown which kill the look and feel of the application. This patch replaces the UUID with a more explanatory string.

#### Summary

#### Ticket Link

2022-02-17 09:51 UTC, mattermod commented
Hello @akkivasu,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-02-18 06:14 UTC, akkivasu commented
/check-cla

2022-02-21 08:21 UTC, wiggin77 commented
Hi @akkivasu.  We would need to localize this string, and it may be easier for now to do that on the client side.  Also I would like our PM to weight on whether it would be better to store a username with the userID so we can display something more meaningful.  cc @wuwinson

2022-02-22 22:15 UTC, wuwinson commented
@akkivasu @wiggin77 Agreed that showing the username would be more meaningful than "(Deleted User)", but would be even better if we could display something like "username (Deleted User)", to provide more helpful information.

Simply displaying "(Deleted User)" is still better than our current experience and could be a good first step towards showing it in combination with the username, so I'm okay with what we have here as long as we can iterate on it. cc @asaadmahmood @chenilim

2022-02-22 22:23 UTC, chenilim commented
Thanks @akkivasu! Agree this is a step in the right direction.

I think we can take this as is and I propose filing a separate card or issue to track storing the user name with the user. There are important corner cases to consider for that, e.g. that the authors of cards don't get spoofed. If we were to display the "fallback / unverified" user name, it should be indicated as such.

2022-02-23 14:01 UTC, wiggin77 commented on server/services/store/mattermostauthlayer/mattermostauthlayer.go
> +				//Shows "(Deleted User)" instead of long, unreadable UUID in case the user is not found
```suggestion
				// Shows "(Deleted User)" instead of long, unreadable UUID in case the user is not found
```

2022-02-23 14:28 UTC, wiggin77 approved these changes

2022-03-02 13:59 UTC, sbishel requested changes
This string should be translatable. Also please run `npm run i18n-format` to create the string in the english file.

2022-03-02 13:59 UTC, sbishel commented on server/services/store/mattermostauthlayer/mattermostauthlayer.go
> +				username := "(Deleted User)"
This should use `intl.Format()` so it will be translated.

2022-03-03 19:37 UTC, sbishel commented
Actually, @wiggin77 pointed out, we do not yet have translations on the server side. Accepting this PR as is for now.

2022-03-03 19:37 UTC, sbishel approved these changes

2022-03-03 19:38 UTC, merged

2022-03-03 19:38 UTC, mattermod commented
Cherry pick is scheduled.