Add Members History support
mattermost/focalboard pull request #2595
Opened 2022-03-23 10:13 UTC by jespino

2022-03-23 10:15 UTC, jespino commented on server/services/store/sqlstore/board.go
> +func (s *SQLStore) getBoardMemberHistory(db sq.BaseRunner, boardID, userID string, limit uint64) ([]*model.BoardMemberHistoryEntry, error) {
This function and the `boardMemberHistoryEntriesFromRows` are just to be able to test it properly as part of the store, also, we are going to need something like that for the compliance export sooner than later, so I'm doing it anyway.

2022-03-23 10:33 UTC, jespino commented on server/services/store/sqlstore/board.go
> +	oldMember, _ := s.getMemberForBoard(db, bm.BoardID, bm.UserID)
This is not amazing, but is the simplest approach that I found to detect if this is an insert or an update.

2022-03-23 18:23 UTC, jespino commented
/update-branch

2022-03-23 20:45 UTC, chenilim requested changes
I've updated the spec to reflect this implementation. Please review. One requested change: "deleted" instead of "delete".

2022-03-23 20:45 UTC, chenilim commented on server/services/store/sqlstore/board.go
> +			Values(boardID, userID, "delete", model.GetMillis())
Let's make this "deleted" to be consistent with "created".

2022-03-25 18:41 UTC, wiggin77 commented
/update-branch

2022-03-25 18:59 UTC, jespino commented on server/services/store/sqlstore/board.go
> +	oldMember, _ := s.getMemberForBoard(db, bm.BoardID, bm.UserID)
fair point

2022-03-25 19:02 UTC, jespino commented on server/services/store/sqlstore/board.go
> +	oldMember, _ := s.getMemberForBoard(db, bm.BoardID, bm.UserID)
Done.

2022-03-28 20:13 UTC, chenilim approved these changes
Looks good, thanks!

2022-03-29 08:17 UTC, merged