Set type as private for onboarding board
mattermost/focalboard pull request #2687
Opened 2022-03-30 08:45 UTC by harshilsharma63

Fixes #2661

2022-03-30 15:03 UTC, sbishel requested changes

2022-03-30 15:03 UTC, sbishel commented
/update-branch

2022-03-31 06:24 UTC, harshilsharma63 commented on server/app/onboarding.go
> +
We already have `asTemplate` modifier in `DuplicateBoard`, I don't want to add another `asType` modifier in the params.

I think we can create a ticket to handle this in the next release. I'm thinking of replacing the `toTeam` and `asTemplate` params of `duplicateBoard` with `model.BoardPatch`. That we can perform any level of modification while duplicating. For example, updating the title to add a ` (copy)` suffix to duplicated board. Would that be okay for now?

2022-03-31 06:29 UTC, harshilsharma63 commented on server/app/onboarding.go
> +
Created item for today's discussion as well - https://community-daily.mattermost.com/boards/workspace/b1ni7nprjpfwpb566k1gk8z9nw/886d2280-e88e-4065-8c85-1b62578f192e/f30dcb19-a0e8-45d2-8768-a9489f6e7fe8/cndz3kohx3by4pn74y6jci69jko

2022-04-04 07:54 UTC, jespino approved these changes
LGTM

2022-04-04 15:43 UTC, sbishel approved these changes

2022-04-04 15:43 UTC, sbishel commented
/update-branch

2022-04-04 21:11 UTC, merged