GH-2708 - Updating permissions dropdown
mattermost/focalboard pull request #2726
Opened 2022-04-05 11:19 UTC by asaadmahmood

#### Summary
GH-2708 - Updating permissions dropdown

#### Ticket Link
Fixes #2708 

<img width="614" alt="Screenshot 2022-04-05 at 4 15 19 PM" src="https://user-images.githubusercontent.com/11034289/161742792-d0dd6680-971a-499f-9e57-346dce0ac828.png">

2022-04-05 16:41 UTC, sbishel requested changes

2022-04-05 16:41 UTC, sbishel commented on webapp/src/components/__snapshots__/addContentMenuItem.test.tsx.snap
> +      class="false"
I don't think this is right.

2022-04-05 16:41 UTC, sbishel commented on webapp/src/widgets/menu/textOption.tsx
> +            <div className={`${check ? 'menu-option__check' : 'false'}`}>{icon ?? <div className='noicon'/>}</div>
I don't think className should be set if `check=false`, probably at least set to empty('') rather than false.

2022-04-07 05:10 UTC, harshilsharma63 commented
The menu option works great! No issue other than not adding the `false` class as Scott already mentioned.

2022-04-07 05:10 UTC, harshilsharma63 submitted a review, later dismissed
The menu option works great! No issue other than not adding the false class as Scott already mentioned.

2022-04-07 20:45 UTC, asaadmahmood commented
@harshilsharma63 @sbishel This should be fixed.

2022-04-07 23:27 UTC, sbishel approved these changes

2022-04-07 23:53 UTC, merged