fix: hide 'Copy link' for `single-user` installs
mattermost/focalboard pull request #2761
Opened 2022-04-11 19:23 UTC by Pinjasaur

#### Summary

Hides instances of the `Copy link` button for `single-user` installs e.g. Personal Desktop.

#### Ticket Link

closes #2337

2022-04-11 19:23 UTC, mattermod commented
Hello @Pinjasaur,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-04-11 21:14 UTC, chenilim approved these changes
Looks good! On the eslint settings: Looks like the default Mattermost rules were removed in the permissions-branch, so the quotes (and other rules) aren't currently being checked for.

2022-04-12 21:55 UTC, sbishel requested changes
@Pinjasaur - I would update "single-user" with 'single-user', because we know that lint will complain about them but don't worry about fixing esLint as part of this PR. I will create a ticket for that.

2022-04-13 16:33 UTC, sbishel approved these changes

2022-04-13 16:33 UTC, merged

2022-04-13 16:36 UTC, pfltdv commented
/check-cla