Sorted categories on modification or creation
mattermost/focalboard pull request #2856
Opened 2022-04-20 14:25 UTC by harshilsharma63

Fixes #2809

2022-04-20 16:57 UTC, sbishel requested changes

2022-04-20 16:57 UTC, sbishel commented on webapp/src/store/sidebar.ts
>          },
Should only sort once.
```suggestion
            })
            // sort categories alphabetically
            state.categoryAttributes.sort((a, b) => a.name.localeCompare(b.name))
        },
```

2022-04-21 08:42 UTC, harshilsharma63 commented on webapp/src/store/sidebar.ts
>          },
Done.

2022-04-22 14:29 UTC, Pinjasaur approved these changes
LGTM

2022-04-22 16:48 UTC, sbishel approved these changes

2022-04-22 16:48 UTC, merged