Refactor websockets state and lifecycle
mattermost/focalboard pull request #3315
Opened 2022-07-06 10:30 UTC by mgdelacroix

#### Summary
This PR moves the state of the authentication and subscriptions to the websockets client, allowing for multiple components to communicate with it and request subscriptions independently. With this change, the lifecycle of the websockets client is now managed on a component, and a hook is provided for easy access to it from individual components.

These changes allow as well for components exported through the plugin API to use the Focalboard websockets client.

2022-07-07 07:58 UTC, jespino reviewed
I like what I see here, the interface is much cleaner

2022-07-13 08:29 UTC, harshilsharma63 requested changes

2022-07-13 08:29 UTC, harshilsharma63 commented on server/services/store/sqlstore/board.go
> +func (s *SQLStore) searchBoardsForUserInTeam(db sq.BaseRunner, teamID, term, userID string) ([]*model.Board, error) {
This is almost completely a copy of `SearchBoardsForUser` in MM auth layer. Can one function re-use the other one as the only difference is including team id check?

2022-07-13 08:29 UTC, harshilsharma63 commented on server/services/store/sqlstore/board.go
> +func (s *SQLStore) searchBoardsForUserInTeam(db sq.BaseRunner, teamID, term, userID string) ([]*model.Board, error) {
This is for both store and app layers.

2022-07-13 09:44 UTC, harshilsharma63 approved these changes

2022-07-13 09:44 UTC, harshilsharma63 commented
The comments can be addressed in a separate PR, independent from this.

2022-07-14 10:31 UTC, merged