Converted synthetic membership to natuaral for board's channel members
mattermost/focalboard pull request #3390
Opened 2022-07-20 11:17 UTC by harshilsharma63

Fixes #3369

2022-07-20 12:30 UTC, mgdelacroix requested changes
Code is looking good! could you please add an integration test for the use case?

2022-07-22 02:18 UTC, harshilsharma63 commented
@mgdelacroix I've added unit test for app later to cover this case.

2022-07-22 13:40 UTC, mgdelacroix approved these changes
LGTM! :+1: Minor, nonblocking nit

2022-07-22 13:40 UTC, mgdelacroix commented on server/app/boards_test.go
> +		}, nil)
nit: you can return directly the board member you've created:

```suggestion
		th.Store.EXPECT().GetMemberForBoard(boardID, userID).Return(boardMember, nil)
```

2022-07-27 05:19 UTC, harshilsharma63 commented
> LGTM! 👍 Minor, nonblocking nit

Actually, the two are not the same. One is synthetic and the other isn't.

2022-07-27 18:16 UTC, sbishel commented
/update-branch

2022-07-27 21:34 UTC, merged

2022-07-27 21:34 UTC, mattermod commented
Cherry pick is scheduled.