Duplicate board retain category
mattermost/focalboard pull request #3395
Opened 2022-07-21 06:31 UTC by harshilsharma63

Fixes #2897

2022-07-27 17:37 UTC, sbishel requested changes
Although it ends up correct, there is an obvious flash when the category is updated after being copied. See attached video.

https://user-images.githubusercontent.com/12704875/181312887-378a2b08-3111-40fd-a547-48d763c193e7.mov

2022-08-01 06:06 UTC, harshilsharma63 commented
@sbishel That's happening because the WS events for new board creation and moving the board to the category is sent to the client very close to each other, and sometimes it ends up processing one before the other. Need to see how to handle this.

2022-08-03 20:41 UTC, sbishel commented
> @sbishel That's happening because the WS events for new board creation and moving the board to the category is sent to the client very close to each other, and sometimes it ends up processing one before the other. Need to see how to handle this.

Seems we should try to do this in a single update or possibly not send the websocket message until both updates are complete.

2022-08-09 21:44 UTC, Pinjasaur approved these changes
LGTM @harshilsharma63. I'm going to defer merging in case @sbishel had any further feedback.

2022-08-09 21:44 UTC, Pinjasaur commented on webapp/src/components/sidebar/sidebarBoardItem.tsx
> +        if (props.categoryBoards.id !== '') {
Thanks for the explanation! 🙂

2022-08-09 22:57 UTC, sbishel approved these changes

2022-08-10 11:01 UTC, harshilsharma63 commented
> LGTM @harshilsharma63. I'm going to defer merging in case @sbishel had any further feedback.

Merging as Scott approved.

2022-08-10 11:01 UTC, merged

2022-08-10 11:01 UTC, mattermod commented
Cherry pick is scheduled.