Added role so that the non-admin will not be able to unlink the board
mattermost/focalboard pull request #3703
Opened 2022-08-18 10:50 UTC by Rajat-Dabade

#### Summary
This PR will add functionality to not allow non-admin to unlink the board from rhs-channel

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/3600

2022-08-18 16:13 UTC, sbishel requested changes
Is there a reason you didn't use <BoardPermissionGate>? I think you simply need to wrap the <MenuWrapper> in a <BoardsPermissionGate> like was done here.
https://github.com/mattermost/focalboard/blob/main/webapp/src/components/shareBoard/userPermissionsRow.tsx#L57

Also we should avoid mixing Bug fixes with UI Enhancements.

2022-08-19 05:01 UTC, Rajat-Dabade commented
Thanks for the feedback @sbishel, it was my bad I was not aware of the `invert` prop. I have made the changes and pushed it. And regarding the UI changes, It was needed for this PR and also confirmed it with @asaadmahmood. Should we go forward with it?

2022-08-19 09:08 UTC, asaadmahmood commented
I think @sbishel is more referring to some other minor UI changes I did on the side.
Noted Scott. I also fixed some UI bugs as well in this, that may have taken more time to create an issue and a PR (like the linked boards in the channels RHS not being theme compatible, etc).

And some spacing/sizing issues.

When I work on a part of the code, I also see if the UI on that part can also be improved if its just a few lines of fix.

2022-08-19 14:43 UTC, sbishel requested changes
@rajat @asaadmahmood - Please revert all of the UX fixes in this PR. This PR should be essentially a 3 code line/3 file change. Instead there are 38 files that have changed. I would like the UX changes pulled out separately into another PR. 

I'm ok with doing minor UI fixes in with a PR that is implementing a new feature. But when it is a bug fix, I would like to restrict those to fixing the issue. When a "minor" UI fix causes 30+ snapshot files to change, then it should be in its own PR. These changes in this PR cause it go from a couple files being changed to 38 files. On this PR, I feel 5/5 on this.

2022-08-19 14:43 UTC, sbishel commented on mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
> +                        </BoardPermissionGate>
This section should be deleted.

2022-08-19 17:01 UTC, sbishel commented
@Rajat-Dabade @asaadmahmood - Sorry, I didn't read what the entire fix entailed. I just expected the menu item to be hidden. Sorry for that confusion. I don't like the feature. We don't disable menus anywhere else that I know of or tell users they can't do something because they are not an admin. But ignore my comments for now. It looks good base on the instructions in the PR....sorry.

2022-08-22 13:15 UTC, sbishel approved these changes
Approving from a code perspective.

2022-08-22 21:28 UTC, sbishel commented
@Rajat-Dabade - Ready to merge

2022-08-23 04:38 UTC, rajat commented
Kindly, remove me from the github.
My github handle is rajat.
I am not part of this thread.


Thanks and Regards,
Rajat Kumar

On Tue, Aug 23, 2022, 02:58 Scott Bishel ***@***.***> wrote:

> @Rajat-Dabade <https://github.com/Rajat-Dabade> - Ready to merge
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mattermost/focalboard/pull/3703#issuecomment-1223095949>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC4MQ3KFXLCUA3H4XXAKDI3V2PWIJANCNFSM564XFOCA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-23 11:31 UTC, merged