Update app bar tooltip text to `Toggle Linked Boards`
mattermost/focalboard pull request #3705
Opened 2022-08-18 19:16 UTC by Pinjasaur

#### Summary

![image](https://user-images.githubusercontent.com/6335792/185475851-b3ae234d-7033-4e7a-aebc-2c97749b670f.png)

#### Ticket Link

closes #3659

2022-08-18 19:17 UTC, Pinjasaur commented
cc @lindy65, not sure if you're using the app bar in the Rainforest test servers

2022-08-18 19:49 UTC, sbishel requested changes

2022-08-18 19:49 UTC, sbishel commented on mattermost-plugin/webapp/src/index.tsx
> +                this.registry.registerAppBarComponent(appBarIconURL, () => mmStore.dispatch(toggleRHSPlugin), 'Toggle Linked Boards')
This should be translated. Yes, it was an issue before as well.

2022-08-18 21:26 UTC, Pinjasaur commented
@sbishel done—tried modelling it after Playbooks' i.e. `<FormattedMessage>` (https://github.com/mattermost/mattermost-plugin-playbooks/blob/d0d704cb446a2bdd075ab61e943465a417c93ba9/webapp/src/components/channel_header.tsx#L40) but that wasn't working as-is (seemed to need a ancestor `<IntlProvider>` component) so I tried `createIntl` using the i18n logic we already have within Focalboard as a product

2022-08-19 06:45 UTC, lindy65 commented
Thanks for the heads-up @Pinjasaur :) Currently, we're not using the apps bar in Rainforest.

2022-08-19 13:35 UTC, wiggin77 commented on webapp/i18n/en.json
> +  "Filter.contains": "contains",
Wow.  It looks like 118n extraction hadn't been run in a while.  We should add that to our CI/lint.

2022-08-19 13:36 UTC, wiggin77 commented on webapp/i18n/en.json
> +  "Filter.contains": "contains",
I'll create a ticket for that.

2022-08-19 13:36 UTC, wiggin77 approved these changes
LGTM :+1:

2022-08-19 14:50 UTC, sbishel approved these changes
@Pinjasaur - Lots of work for such a minor change. :)

2022-08-19 18:18 UTC, merged