Escape button close the boardSelector dialog
mattermost/focalboard pull request #3850
Opened 2022-09-15 09:02 UTC by Rajat-Dabade

#### Summary
The PR adds a key binding for the `Escape` key for closing the BoardSelector Dialog in the channel's board linker.

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/3510

2022-09-21 06:26 UTC, harshilsharma63 requested changes

2022-09-21 06:26 UTC, harshilsharma63 commented on mattermost-plugin/webapp/src/components/boardSelector.tsx
> +        console.log(event.key)
Remove log. Can we also add a test for this?

2022-09-30 15:29 UTC, sbishel commented
@Rajat-Dabade - Lets get this finished up and merged.

2022-10-04 10:08 UTC, harshilsharma63 approved these changes

2022-10-04 16:37 UTC, sbishel commented
@Rajat-Dabade - Please merge.

2022-10-04 16:50 UTC, merged