[MM-45052] Add error checking in insights API
mattermost/focalboard pull request #3876
Opened 2022-09-20 15:54 UTC by cyrilzhang-mm

#### Summary

#### Ticket Link

2022-09-25 13:41 UTC, plant99 approved these changes

2022-09-25 13:45 UTC, plant99 requested changes

2022-09-25 13:45 UTC, plant99 commented on server/api/insights.go
> +		a.errorResponse(w, r, appErr)
Can we create a new error with `ErrBadRequest` with just message from `appErr`? Same for the changes in user boards insights?

2022-09-29 15:59 UTC, BenCookie95 approved these changes
Nice work!

2022-09-30 00:21 UTC, sbishel approved these changes

2022-09-30 04:07 UTC, plant99 approved these changes

2022-09-30 15:29 UTC, sbishel commented
Is this ready to merge?

2022-09-30 15:32 UTC, cyrilzhang-mm commented
> Is this ready to merge?

No, the corresponding PR has not been merged in mattermost-server yet. We need to merge the PRs together, as discussed here:
https://github.com/mattermost/mattermost-server/pull/21048#issuecomment-1262492850

2022-10-12 17:23 UTC, BenCookie95 approved these changes

2022-10-17 05:56 UTC, plant99 approved these changes

2022-10-25 14:26 UTC, cyrilzhang-mm commented
/update-branch

2022-11-14 19:53 UTC, furqanmlk approved these changes

2022-11-18 16:11 UTC, merged