Fix misaligned 'viewer' role on share board/template dialog
mattermost/focalboard pull request #3926
Opened 2022-10-04 16:06 UTC by vivekkj123

#### Summary

The viewer button on share dialog was misaligned due to it was missing the `empty-icon` whenever the `currentRole` is not equal to `Viewer` role. This PR fixes it. (Attaching before and after screenshots)

Before

![before](https://user-images.githubusercontent.com/58988126/193869525-941c767b-a9b8-41f2-bd78-e41bb70e5a3e.png)

After

![after](https://user-images.githubusercontent.com/58988126/193869546-925d21bf-0ec3-4ad8-bdee-78d05c714bd8.png)

#### Ticket Link

Fixes https://github.com/mattermost/focalboard/issues/3865

2022-10-04 16:06 UTC, mattermod commented
Hello @vivekkj123,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-04 19:02 UTC, sbishel requested changes
Thanks @vivekkj123 - changes look good, but requires some snapshots to be updated. 

`npm test -- -u`

2022-10-05 04:50 UTC, vivekkj123 commented
@sbishel Done 👍🏼

2022-10-05 14:49 UTC, sbishel approved these changes

2022-10-05 14:49 UTC, sbishel commented
@vivekkj123 - Thanks for your contribution.

2022-10-05 14:49 UTC, merged