Fixed the CSV export for created by property
mattermost/focalboard pull request #4348
Opened 2022-12-15 12:49 UTC by Rajat-Dabade

#### Summary
This PR fixes the export value for `createdBy` property for cards.

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/4134

2022-12-16 11:33 UTC, jespino requested changes
I guess that happens also with the `updatedBy`, the `createdAt` and `updatedAt`, right?

2022-12-22 13:29 UTC, Rajat-Dabade commented
@jespino, it is working for `Created time` and `Updated time`. The value is not exported for `Last updated by`. Nice catch.

2022-12-23 09:33 UTC, jespino approved these changes
LGTM

2022-12-28 07:07 UTC, merged

2022-12-28 07:07 UTC, mattermod commented
Cherry pick is scheduled.

2022-12-28 07:07 UTC, mattermod commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/focalboard
   625a3e12..96b79067  compliance-history-export -> upstream/compliance-history-export
   d04dabd1..f7eba992  hide-board-scale -> upstream/hide-board-scale
   0762cb7d..bad0e5b1  main             -> upstream/main
   7cca97cf..17d57dfd  release-7.7      -> upstream/release-7.7
   401062d1..6e69de07  rolling-stable   -> upstream/rolling-stable
   543c9695..4a858b79  website-update   -> upstream/website-update
Fetching origin
Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6-1672211247
Switched to a new branch 'automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6-1672211247'
Branch 'automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6-1672211247' set up to track remote branch 'release-7.6' from 'upstream'.

+++ About to attempt cherry pick of PR #4348 with merge commit bad0e5b1de8644855f21dd5ac659115453f4d4cf.

[automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6-1672211247 9bd96433] Fixed the CSV export for created by property (#4348)
 Author: Rajat Dabade <rajat.dabade@mattermost.com>
 Date: Wed Dec 28 12:37:24 2022 +0530
 1 file changed, 7 insertions(+), 1 deletion(-)

+++ I'm about to do the following to push to GitHub (and I'm assuming origin is your personal fork):

  git push origin automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6-1672211247:automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6

Failed to add the RSA host key for IP address '140.82.112.3' to the list of known hosts (/app/.ssh/known_hosts).
remote: 
remote: Create a pull request for 'automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6' on GitHub by visiting:        
remote:      https://github.com/mattermost-build/focalboard/pull/new/automated-cherry-pick-of-focalboard-%234348-upstream-release-7.6        
remote: 
To github.com:mattermost-build/focalboard.git
 * [new branch]        automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6-1672211247 -> automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6

+++ Creating a pull request on GitHub at mattermost-build:automated-cherry-pick-of-focalboard-#4348-upstream-release-7.6
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "base"

+++ Returning you to the main branch and cleaning up.

```