Menu consistent for table view
mattermost/focalboard pull request #4392
Opened 2022-12-22 13:15 UTC by Rajat-Dabade

#### Summary
This PR will make the menu options consistent for the table row. Previously it was only showing the `Delete` card button, now it will show as it is in the kanban view i.e. `Delete`, `Duplicate` and `copy link` options. 

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/4281

2022-12-22 17:37 UTC, sbishel requested changes
Hey Rajat.  From a base standpoint the fix looks good. But let's go ahead and clean up a few things while where here.

Check a couple things... Do all "paths" for `duplicate card` and `delete card` provide telemetry? I don't think all `delete card` paths do.  Also, to that end. Let's move the telemetry calls to the  `CardActionMenu`. I think this is doable.

Then investigate if we can move the delete/duplicate code into the `CardActionMenu`. I didn't examine every case, but I think this is at least partially doable. Or perhaps provide a default implementation.

I realize, not all of this is directly necessary for fixing the bug, but lets go ahead and clean-up this code where it makes sense and doesn't require large effort.

2022-12-28 05:05 UTC, Rajat-Dabade commented on webapp/src/components/table/tableRow.tsx
> +    showCard: (cardId?: string) => void
We have a cardId set to `undefined` so that if an API call fails to create a duplicate card it should pass `undefined` to the showCard function.

2022-12-28 05:05 UTC, Rajat-Dabade commented on webapp/src/components/table/tableRow.tsx
> +                            cardId={card!.id}
Got it. Thanks

2022-12-28 05:05 UTC, Rajat-Dabade commented on webapp/src/components/table/tableRow.tsx
> +                                    'duplicate card',
Sure

2022-12-28 16:01 UTC, sbishel approved these changes
NIce updates. LGTM

2022-12-28 16:01 UTC, sbishel commented
/update-branch

2023-01-04 09:45 UTC, merged

2023-01-04 09:45 UTC, mattermod commented
Cherry pick is scheduled.

2023-01-04 21:43 UTC, sbishel commented
Remove the CP. As this isn't necessary for v7.7.0.