Removes product reference from the boardsapp start logline
mattermost/focalboard pull request #4533
Opened 2023-01-31 15:30 UTC by mgdelacroix

#### Summary
`boardsapp` can be started in both product or plugin modes, so the product reference can be misleading. As maintaining both targets is something temporal, I've chosen to remove the product reference. To see if the backend belongs to the product or the plugin, we have to check the log data for the `product` or the `plugin_id` keys respectively:

```
# product logline
{"timestamp":"2023-01-31 16:26:43.096 +01:00","level":"info","msg":"Boards backend successfully started.","caller":"boards/boardsapp.go:180","product":"boards"}

# plugin logline
{"timestamp":"2023-01-31 16:29:34.497 +01:00","level":"info","msg":"Boards backend successfully started.","caller":"app/plugin_api.go:973","plugin_id":"focalboard"}
```

2023-01-31 17:58 UTC, wiggin77 requested changes
I'll wait until the small changes we discussed are ready.

2023-02-01 11:12 UTC, mgdelacroix commented
@sbishel re-requesting review as the approach has changed

2023-02-01 12:34 UTC, wiggin77 approved these changes
LGTM 👍

2023-02-06 17:01 UTC, sbishel approved these changes

2023-03-15 12:50 UTC, closed without merging