Fix cards not deleting properly.
mattermost/focalboard pull request #4746
Opened 2023-05-25 15:29 UTC by crspeller

#### Summary
Fixes cards not deleting properly.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51879

2023-05-25 17:43 UTC, sbishel requested changes
A couple minor things, clean up.

2023-05-25 22:13 UTC, crspeller commented on server/app/blocks.go
> +
Yup. All that logic got moved to the store along with a version of this function.

2023-05-25 22:14 UTC, crspeller commented on server/services/store/sqlstore/blocks.go
> +	}
Yup I guess we can.

2023-05-26 20:05 UTC, sbishel approved these changes

2023-05-30 17:11 UTC, calebroseland approved these changes

2023-05-30 17:21 UTC, sbishel commented
Will need to cp -> release-7.10, release-7.9, release-7.8.

2023-05-31 10:17 UTC, esarafianou approved these changes
LGTM!

2023-05-31 14:26 UTC, merged

2023-05-31 14:39 UTC, sbishel commented
/cherry-pick release-7.10

2023-05-31 14:39 UTC, mattermost-build commented
Cherry pick is scheduled.

2023-05-31 14:39 UTC, mattermost-build commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
From github.com:mattermost/focalboard
   252f2138..c3b1c82b  main               -> upstream/main
 * [new branch]        cloud-2023-05-19-backup -> upstream/cloud-2023-05-19-backup
 * [new branch]        cloud-2023-05-24-backup -> upstream/cloud-2023-05-24-backup
   8de46aff..265529c3  release-7.1        -> upstream/release-7.1
   df5456ad..304afa9e  release-7.10       -> upstream/release-7.10
   6fc1d9f8..134be30d  release-7.8        -> upstream/release-7.8
   6556a8dd..70893582  release-7.9        -> upstream/release-7.9
 * [new branch]        remove-product-references -> upstream/remove-product-references
 * [new tag]           cloud-2023-05-22-1 -> cloud-2023-05-22-1
 * [new tag]           cloud-2023-05-23-1 -> cloud-2023-05-23-1
Fetching origin
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/app/.ssh/known_hosts).
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-focalboard-#4746-upstream-release-7.10-1685543983
Switched to a new branch 'automated-cherry-pick-of-focalboard-#4746-upstream-release-7.10-1685543983'
Branch 'automated-cherry-pick-of-focalboard-#4746-upstream-release-7.10-1685543983' set up to track remote branch 'release-7.10' from 'upstream'.

+++ About to attempt cherry pick of PR #4746 with merge commit c3b1c82b1a6727c6eb69c611c6316cc555bc0f9a.

error: could not apply c3b1c82b... Fix cards not deleting properly. (#4746)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

+++ Conflicts detected:

UU server/app/blocks.go
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the main branch and cleaning up.

```