Update community supported README
mattermost/focalboard pull request #4914
Opened 2023-10-25 13:42 UTC by cwarnermm

Added legal-approved disclaimer (bolded).

Preview
![image](https://github.com/mattermost/focalboard/assets/74422101/dbb2f316-92d9-42d3-ab00-376ce7ac3194)

2023-10-25 15:44 UTC, esethna requested changes

2023-10-25 15:44 UTC, esethna commented on README.md
>  Self-hosted Mattermost instances may continue to use the Focalboard plugin without interruption; however, Mattermost developers will not be adding any new enhancements or bug fixes beyond September 1
Effective September 15th, 2023, the Focalboard plugin is no longer bundled with Mattermost. Self-hosted Mattermost....

2023-10-25 15:44 UTC, esethna commented on README.md
> +Effective September 15th, 2023, the Focalboard plugin is no longer bundled with Mattermost and has transitioned to being fully community supported.
propose removing this and moving down to minimize duplication with the legal statement

2023-10-25 15:45 UTC, esethna commented on README.md
>  # :warning: Announcements
Should this be "Disclaimer" rather than "Announcements"?

2023-10-25 15:54 UTC, esethna approved these changes

2023-10-26 21:22 UTC, sbishel approved these changes

2023-12-08 17:28 UTC, cwarnermm commented on README.md
> +# :warning: Disclaimer
```suggestion
# Disclaimer
```

2023-12-08 17:28 UTC, cwarnermm commented on README.md
> +**This repository is community supported and not maintained by Mattermost. Mattermost disclaims any and all liability for integrations, including Third Party Integrations and Mattermost Integrations.
```suggestion
**This repository is community supported and not maintained by Mattermost. Mattermost disclaims liability for integrations, including Third Party Integrations and Mattermost Integrations. Integrations may be modified or discontinued at any time.**
```

2023-12-08 17:29 UTC, cwarnermm commented
Legal's updated guidance and language for the legal disclaimer for community-supported integrations has been applied to this PR.

2023-12-08 17:36 UTC, esethna approved these changes
Thanks Carrie!

2023-12-19 14:30 UTC, merged