Enhance Readme To Explain How To Contribute Translations
mattermost/focalboard pull request #4918
Opened 2023-10-29 18:38 UTC by TomerPacific

#### Summary
Mattermost Boards has transitioned to a community supported plugin called [Focalboard](https://github.com/mattermost/focalboard). This plugin's string translations are no longer managed using the [Mattermost Translation Server](https://translate.mattermost.com/).

This PR aims to update the section in the README about contributing translations with all the necessary steps.

#### Ticket Link

 Fixes [Issue #6656](https://github.com/mattermost/docs/issues/6656)

2023-10-29 18:38 UTC, mattermost-build commented
Hello @TomerPacific,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-30 13:05 UTC, cwarnermm commented
Thanks, @TomerPacific! Curious to understand why you edited the snap files as part of this PR?

2023-10-30 14:43 UTC, sbishel requested changes
I'm fine with the readme changes, but the snapshots shouldn't be changed...they are causing test failures.

2023-10-30 18:41 UTC, TomerPacific commented
@cwarnermm - My apologies, I saw @ctlaltdieliet's comment about having to run the snapshot command and I thought I might need to do that as well for this PR. I'll revert the changes.

2023-10-30 18:54 UTC, cwarnermm commented
Thanks, @TomerPacific! The snapshot command details make sense to include as part of this PR, just not the outcome/impact of running the command itself :)

2023-10-30 19:44 UTC, ctlaltdieliet approved these changes
lgtm!
Thanks @TomerPacific for your clear instructions on how to contribute to the translations and adding a new language! 
Great work

2023-10-30 20:35 UTC, cwarnermm approved these changes
Really appreciate your help with this, @TomerPacific!! Thank you!

2023-10-31 13:53 UTC, sbishel approved these changes

2023-10-31 13:53 UTC, sbishel commented
Windows build issues are known..

2023-10-31 13:53 UTC, merged