Add non-breaking space before 'show description button'
mattermost/focalboard pull request #604
Opened 2021-06-19 11:27 UTC by lunaticmonk

#### Summary
Adds a space between the "show description" description and the icon on a board.

#### Ticket Link
https://github.com/mattermost/focalboard/issues/535

2021-06-19 11:53 UTC, lunaticmonk commented
@chenilim I have signed the CLA but I don't know how to re-trigger the workflows to let the cla/mattermost workflow pass. Can you please help me out?

2021-06-19 17:45 UTC, chenilim commented
/check-cla

2021-06-21 04:08 UTC, lunaticmonk commented
![image](https://user-images.githubusercontent.com/17925669/122705970-6788f400-d274-11eb-9ace-f20543ce6994.png)

Here is the screenshot of the fix.

2021-06-21 04:09 UTC, lunaticmonk commented
@chenilim Can you please review?

![image](https://user-images.githubusercontent.com/17925669/122705970-6788f400-d274-11eb-9ace-f20543ce6994.png)

2021-06-21 09:29 UTC, jespino commented on webapp/src/components/viewTitle.tsx
> +                        &nbsp;
I don't love the use of `&nbsp;` here, it remove certain control of the styling, do you mind to add a `.ViewTitle .add-buttons .Icon` css that add a `margin-right`, that way we can make more fine grain styling of this.

2021-06-21 09:29 UTC, jespino requested changes
I prefer to go with css intead of `&nbsp` for this visual bug.

2021-06-21 09:30 UTC, jespino commented on webapp/src/components/viewTitle.tsx
> +                        &nbsp;
by the way, the right place would be the file `webapp/src/components/viewTitle.scss`

2021-07-02 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-07-07 06:01 UTC, harshilsharma63 commented
@lunaticmonk just checking in if you have any update on this?

2021-07-11 10:34 UTC, lunaticmonk commented
@harshilsharma63 @jespino Pushed the css changes. Please review once.

2021-07-12 08:03 UTC, jespino requested changes

2021-07-12 08:03 UTC, jespino commented on webapp/src/components/viewTitle.scss
> +    .non-breaking-space {
This is not what I was expecting, I was thinking more in something like changing the already existing `.add-buttons .Icon` class and add there the `margin-right: 0.5em`, that way you don't need the `span` element at all, and you also fix the same problem with the `Hide` and `Emoji` icons.

2021-07-29 17:37 UTC, sbishel commented
@lunaticmonk Just checking in if you are still working on this.

2021-07-31 16:36 UTC, lunaticmonk commented
@sbishel Yes, will update this PR soon, was a bit busy from few days at work!

2021-08-12 07:33 UTC, lunaticmonk commented
@sbishel I accidently logged out of my account on my local setup and can't remember the password. Is there a way to reset the password via some hack? I need to test these changes once. I also tried signing up again but getting:

![image](https://user-images.githubusercontent.com/17925669/129156463-ce8456d1-8f00-4a01-9cc2-4b4bf3044d72.png)


Can you help me in this?

2021-08-19 00:04 UTC, sbishel commented
@lunaticmonk Sorry, I missed this message. No, we don't have a hack for that. You could hack the change password code (ie, don't require old password) and run via ChangePassword API. 

I'm not sure why you can't register a new user are you seeing any other errors?

 If you want to push it up this PR, I'm happy to test.

2021-09-01 04:56 UTC, lunaticmonk commented
@sbishel I tried doing few hacks but the page gets redirected to login and I cannot reset password. Looks like I will need your help in testing this and merging it. Meanwhile, I will set up the repo again in my system.

2021-09-01 15:39 UTC, sbishel commented
@lunaticmonk Sure, merge your changes to this PR and I'll test. The only hack would be if your running source code to put a break point in where login fails and go around it.

2021-09-08 02:42 UTC, lunaticmonk commented
@sbishel Didn't get you? Which PR should I merge my changes to? Is there any other branch you have where I should merge these?

2021-09-08 16:13 UTC, sbishel commented
@lunaticmonk This one. I thought you had additional updates to this PR based on Jesus feedback.

2021-09-08 16:21 UTC, lunaticmonk commented
@sbishel These are the only changes I believe. You can test this branch.

2021-09-08 21:55 UTC, sbishel commented
Fixed by https://github.com/mattermost/focalboard/pull/765

2021-09-08 21:55 UTC, closed without merging