Add more unit tests for ./store/sqlstore/user.go
mattermost/focalboard pull request #787
Opened 2021-07-26 15:04 UTC by yedamao

#### Summary

Add more unit tests for ./store/sqlstore/user.go

#### Ticket Link

Fixes https://github.com/mattermost/focalboard/issues/430

2021-07-26 15:04 UTC, mattermod commented
Hello @yedamao,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-07-26 20:24 UTC, wiggin77 commented on server/services/store/storetests/users.go
> +		require.Nil(t, err)
```suggestion
		require.NoError(t, err)
```
Same for the other instances below.

2021-07-26 20:26 UTC, wiggin77 requested changes
Looks great @yedamao .  One minor request... use `require.NoError` when checking error cases.

2021-07-27 07:00 UTC, yedamao commented
@wiggin77 PTAL

2021-07-27 15:14 UTC, wiggin77 approved these changes
LGTM :+1:

2021-07-27 15:42 UTC, merged