[GH-526] add copy card link
mattermost/focalboard pull request #795
Opened 2021-07-27 21:42 UTC by majidsajadi

#### Summary
[x] Add a "copy link" option to the card menu, which should simply copy the current URL
[x] Add a "copy link" option to the card menu of the board view, which copy the card URL
[x] Add a "copy link" option to the card menu of the gallery view, which copy the card URL

#### Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/526

2021-07-27 21:42 UTC, mattermod commented
Hello @majidsajadi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-07-27 21:59 UTC, majidsajadi commented
@hahmadia @sbishel I used a temporary `add` icon for the menu icon. please provide a `copy` icon so I can replace it.
also didn't write tests since I'm not sure the implementation would be accepted or not.

2021-07-29 18:24 UTC, sbishel requested changes
Hi @majidsajadi thanks for your contribution. A couple of issues. 

The  "Copy link" menu item does not line up with other menu items.
<img width="243" alt="Screen Shot 2021-07-29 at 12 22 30 PM" src="https://user-images.githubusercontent.com/12704875/127545540-7e778a64-5170-44aa-8145-ea8e51c6c877.png">

Also, I think we should probably create a single reusable component for the menu rather than duplicating the code in three places. There may be some things to work through, but should be fairly straight forward. Let me know if you have questions regarding this.

@asaadmahmood Could you provide a `copy link` icon?

2021-07-30 10:05 UTC, majidsajadi commented
@sbishel about the alignment. It's because the `add` icon is not the same size as the other icons. I will fix this issue when the copy link icon is provided.

about the duplication, do you mean `Menu.Text` or the `onClick` method? if you mean the `onClick` method please let me know your suggestion about where should I create the method. I thought about the `utils` but since it's a card functionality it didn't feel right. also `mutator` is not a good choice since `copyLink` is not mutating anything.

2021-07-30 16:33 UTC, sbishel commented
@majidsajadi - I created a separate ticket for [Creating a Reuseable Menu component](https://github.com/mattermost/focalboard/issues/808). But I'm actually talking about the entire `<Menu>` as a component.  But that can be handled separate from this PR.

Once we get the icon, it should be good to go. Thanks for your contribution.

2021-07-30 16:49 UTC, majidsajadi commented
@sbishel i would like to work on that issue too.

2021-08-02 18:28 UTC, asaadmahmood commented
@hahmadia Here's the icon that we should use:
`icon-link-variant`

You can find it here:
https://mattermost.github.io/compass-icons/

2021-08-02 18:28 UTC, asaadmahmood commented
If you need any css help. let me know.

2021-08-03 13:41 UTC, hahmadia commented
@asaadmahmood 

I think you meant to tag Scott Bishel @sbishel

2021-08-03 18:07 UTC, hahmadia requested changes
Hi @majidsajadi ,

Could you please fix the broken test before I review it. Thank you
```
[tsl] ERROR in /home/runner/work/focalboard/focalboard/webapp/src/components/gallery/galleryCard.tsx(104,82)
      TS2552: Cannot find name 'cardTree'. Did you mean 'cardRef'?
 ```

2021-08-05 23:37 UTC, majidsajadi commented
@asaadmahmood the duplicated and delete icons are plain SVG and not compass icons. so should I go with this compass icon for the copy link or do we have SVG for this copy link icon too?

2021-08-06 06:01 UTC, asaadmahmood commented
@majidsajadi Ideally we can use the compass icon for all 3, if you're working on the compass icon, just go ahead and update the icon for all 3 of those, that would be great.

2021-08-06 10:20 UTC, majidsajadi commented
@asaadmahmood I can do that. but I can't confirm if my changes would break anything or not (especially styles). for example, there are 13 different components that use `DeleteIcon` so if I change this we may encounter some breaks. also `DuplicateIcon`.

2021-08-14 09:31 UTC, majidsajadi commented
> @asaadmahmood I can do that. but I can't confirm if my changes would break anything or not (especially styles). for example, there are 13 different components that use `DeleteIcon` so if I change this we may encounter some breaks. also `DuplicateIcon`.

@asaadmahmood  any update? what should I do? update all components? also `icon-link-variant` is not like  `DeleteIcon and `DuplicateIcon`.

2021-08-14 09:32 UTC, asaadmahmood commented
@majidsajadi You can update them and then send me a message here, or on mattermost, I can then go and do a quick review to see if things look good, or fix the css where it doesn't.

2021-08-20 21:58 UTC, sbishel requested changes
Let's wait until this [PR](https://github.com/mattermost/focalboard/pull/1050) gets merged and retest, we should be able to remove setting the cardID parameter.

2021-08-20 21:58 UTC, sbishel commented on webapp/src/components/gallery/galleryCard.tsx
> +                                const url = Utils.addQueryParamToCurrentURL('c', cardTree.card.id)
When this [PR](https://github.com/mattermost/focalboard/pull/1050) goes in, this line should no longer be necessary.

2021-08-20 21:58 UTC, sbishel commented on webapp/src/components/kanban/kanbanCard.tsx
> +                                const url = Utils.addQueryParamToCurrentURL('c', card.id)
Same, with recent change, card.id is part of the URL.

2021-08-24 13:07 UTC, hahmadia commented
Also could you please fix the tests, thank you!

2021-09-05 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-09-13 19:23 UTC, sbishel requested changes

2021-09-13 19:23 UTC, sbishel commented on webapp/src/components/properties/dateRange/__snapshots__/dateRange.test.tsx.snap
> +        June 15 → June 20
```suggestion
        15 de junio → 20 de junio
```

2021-09-13 19:23 UTC, sbishel commented on webapp/src/components/properties/dateRange/__snapshots__/dateRange.test.tsx.snap
> +        June 15 → June 20
Causing Unit test failure.

2021-09-23 23:14 UTC, sbishel approved these changes

2021-09-23 23:18 UTC, sbishel commented
@hahmadia Would you re-review? It won't let me request a review from you, but also shows you requested changes.

2021-09-24 16:19 UTC, hahmadia approved these changes
Hey @majidsajadi ! I'm really sorry for the long over due review. Been busy around here but I finally got a chance to look at it!

All looks great. There was one minor bug where if I was say in Kanban view and clicked `Copy Link`, it would copy the link to the view instead of the card. Knowing how long this card has been in review for , I decided to not let it delay any further and gave a helping hand with addressing it.

![image](https://user-images.githubusercontent.com/17804942/134708137-44797ada-9410-41b5-a246-111b2845e0aa.png)

Otherwise, thank you for the contribution and sorry for taking so long on reviewing this.

2021-09-24 16:20 UTC, hahmadia commented
Since there aren't MAJOR changes, I believe this is an appropriate PR for QA to test after it has been merged.

2021-09-24 16:26 UTC, merged