[GH-692] Auto-size takes the sort arrow into account
mattermost/focalboard pull request #802
Opened 2021-07-29 15:40 UTC by kamre

#### Summary
Proper computation of total horizontal padding for svg element.

#### Ticket Link
Fixes #692

@sbishel FYI

2021-07-29 15:40 UTC, mattermod commented
Hello @kamre,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-07-29 17:23 UTC, sbishel requested changes
Just minor change for readability, also would you add a unit test for this function.

2021-07-29 17:35 UTC, kamre commented on webapp/src/utils.ts
> +                } else {
@sbishel svg elements have [this type](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString) for className:
![image](https://user-images.githubusercontent.com/5587620/127538297-2ce4c89c-2558-4aae-8a91-55f2797c9b27.png)
How do you propose to move such check inside `switch` statement? We can't compare it with some static object.

2021-07-30 09:09 UTC, kamre commented
@sbishel I would like to add a unit test for `getFontAndPaddingFromCell` but not sure how to do this properly.

Unit test written with help of the testing library [uses JSDOM library internally](https://testing-library.com/docs/dom-testing-library/intro) for the execution of the test. And [JSDOM doesn't have any layout engine](https://github.com/jsdom/jsdom/issues/1322) so it can't compute properly all the style information ([like clientWidth](https://github.com/jsdom/jsdom/issues/2310)) that is used inside `getFontAndPaddingFromCell`.

So how can this function be tested in the unit test?

Can/should we somehow mock [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) for all the elements in the tree that we pass to `getFontAndPaddingFromCell`?

2021-07-30 16:40 UTC, sbishel commented on webapp/src/utils.ts
> +                } else {
I mean to move it above the switch statement -
```
Array.from(children).forEach((element) => {
    if (element.tagName === 'svg') {
        // clientWidth already includes padding
        myResults.padding += element.clientWidth
        myResults.padding += Utils.getHorizontalBorder(style)
        myResults.padding += Utils.getHorizontalMargin(style)
    } else {
       switch (element.className) {
       ...}
    }
}
```

2021-07-30 17:06 UTC, kamre commented on webapp/src/utils.ts
> +                } else {
Agree, this makes sense. Done.

2021-07-30 20:18 UTC, sbishel approved these changes
@kamre - Your right, I don't see an easy way to write tests for these. Thanks for making the other change and your submission.

2021-08-02 06:57 UTC, harshilsharma63 approved these changes

2021-08-02 07:02 UTC, harshilsharma63 commented
This led me to find another bug - the auto-size doesn't work in Firefox. Created #817 for the same.

2021-08-02 07:38 UTC, jespino commented
I'll merge this after the tests passes.

2021-08-02 09:47 UTC, merged