create Dockerfile
mattermost/focalboard pull request #86
Opened 2021-03-18 08:58 UTC by Derrick56007

2021-03-18 08:58 UTC, mattermod commented
Hello @Derrick56007,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-03-18 10:33 UTC, jespino commented
Thanks @Derrick56007 we need you to sign the CLA to accept your PR, anway, somebody already submitted another PR with a preliminary version of the Dockerfile, so if you want to apply changes to that docker file would be really useful.

2021-03-18 10:48 UTC, obbardc requested changes

2021-03-18 10:48 UTC, obbardc commented on Dockerfile
> +    # Go installation
be consistant with spaces vs. tabs

2021-03-18 10:48 UTC, obbardc commented on Dockerfile
> +	&& apt-get install -y curl wget git make gcc g++ ca-certificates --no-install-recommends \
put apt arguments before pacakge names, then sort packages one per line in A-Z order

2021-03-18 10:48 UTC, obbardc commented on Dockerfile
> +RUN make prebuild && make \
new line per command, keep the && on the previous line

2021-03-18 10:48 UTC, obbardc commented on Dockerfile
> +FROM ubuntu:bionic
add to README how to build and run the docker container

2021-03-18 10:49 UTC, obbardc commented
Huh, i completely missed there is already a dockerfile in the main repo. Guess this can be closed

2021-03-18 10:54 UTC, it33 commented
@obbardc thanks for taking the initiative! Are there other ideas or projects you'd be interested in around focalboard?

2021-03-18 14:10 UTC, proffalken commented
> Huh, i completely missed there is already a dockerfile in the main repo. Guess this can be closed

Heh, great minds and all that, I put in a basic one yesterday, completely missed this PR!

The one I created definitely needs some love though, so please make changes as you see fit!

2021-03-29 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-04-05 23:47 UTC, jasonblais commented
Thanks for the contribution!

@jespino is this a duplicate of https://github.com/mattermost/focalboard/pull/76?

2021-04-06 14:54 UTC, jespino commented
Yes, this can be closed, we already have a docker file and actually @flexo3001 is already improving it in another PR.

2021-04-06 14:54 UTC, closed without merging