Adding instructions to download Personal Desktop
mattermost/focalboard pull request #98
Opened 2021-03-18 11:27 UTC by it33

#### Summary

#### Ticket Link

2021-03-18 11:33 UTC, jespino requested changes
I miss here a comment about the Linux installation, looks like only windows or mac users can try it.

Can we add something like "or download the linux binary from the github project releases page: https://github.com/mattermost/focalboard/releases".

2021-03-18 11:53 UTC, it33 commented
Added!

2021-03-19 23:44 UTC, it33 commented
@jespino updated per your suggestion

2021-03-20 07:59 UTC, jespino commented
@it33 still looks like we have no desktop-app in linux, and we have.

2021-03-20 10:33 UTC, it33 commented
@jespino sorry, missed that, added now!

2021-03-20 10:43 UTC, jespino commented on README.md
> +While we don't yet offer installs of **Focalboard Personal Desktop** outside of Store-based installs, it is in [consideration for the future](https://github.com/mattermost/focalboard/issues/99) (plea
I would add a "for mac and windows" to be consistent with the linux paragraph added above

2021-03-20 15:33 UTC, it33 commented
Thanks @jespino makes sense, how about now?

2021-03-20 16:29 UTC, jespino commented
Better, but I was talking about the paragraph talking about not offering the desktop app outside app stores, that is only try for mac and windows, we offer the app in linux to download it directly.

2021-03-20 16:37 UTC, it33 commented
Ah, okay, I think I finally have it. @jespino how's this? 

This thread feels like a scene from a movie I saw once: https://www.youtube.com/watch?v=4IFUYg9IUgI
😃

2021-03-21 09:11 UTC, jespino approved these changes
Now looks good to me. :)

2021-03-21 09:11 UTC, merged