Update i18n.tsx
mattermost/focalboard pull request #980
Opened 2021-08-14 03:15 UTC by leandro-costa

Update i18n.tsx to add all translations of i18n folder

2021-08-14 03:15 UTC, mattermod commented
Hello @leandro-costa,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-08-14 10:15 UTC, leandro-costa commented
/check-cla

2021-08-14 15:28 UTC, jespino commented on webapp/src/i18n.tsx
> +        return messages_zhHans
```suggestion
        return messages_zhHans
```

2021-08-14 15:29 UTC, jespino requested changes
A couple of changes required.

2021-08-14 15:29 UTC, jespino commented on webapp/src/i18n.tsx
> +const supportedLanguages = ['ca', 'de', 'el', 'en', 'es', 'fr', 'id', 'it', 'ja', 'nl', 'oc', 'pt-br', 'ru', 'sv', 'tr', 'zh-cn', 'zh-tw']
You are adding new languages here, but you are not adding them to the Languages menus (in GlobalHeaderMenu and in SidebarMenu)

2021-08-25 14:54 UTC, wiggin77 requested changes
@leandro-costa, will you be able to address the change request left by jespino?

2021-09-05 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-09-30 18:52 UTC, chenilim commented
Trying to clean up stale PRs. @jespino, are there still changes needed? Or can they be made later? Thanks.

2021-10-04 08:03 UTC, jespino commented
@chenilim I guess it can be done later, but I prefer to have everything done in the same PR.

2022-10-19 12:57 UTC, closed without merging